version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "888:80"
    depends_on:
      - flask
  flask:
    build: 
      context: ./app1
      dockerfile: Dockerfile
    # container_name: flask #cant use container name key when scaling as container names == dns names 
    ports:
     - "5000"
    
  #reverse proxy -> loadbalancer 
  #docker-compose down
  # docker-compose up --force-recreate --scale flask=5
  # docker-compose build --no-cache

